version: "3"

services:
  mariadb:
    image: mariadb:10.6.4
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql

volumes:
  data:
